### ISSUE TITLE
Why to use Sigmoid instead of ReLu

### ISSUE THREAD

**Issue by boyw165** [satoshiiizuka/siggraph2016_colorization#14]
Thank you guys for the great idea. I'm not a Torch user so I don't know how to see the graph of the model provided by you. I read the paper and still don't know what networks use Sigmoid or ReLu transfer function. Can you give me the answer? And the reasoning?

**Comment by bobbens** [comment]
It's all ReLU except the last layer which uses Sigmoid so the input is in the [0,1] range.

**Comment by boyw165** [comment]
Thanks. :)
