### ISSUE TITLE
libpng: version warning

### ISSUE THREAD

**Issue by tomkyle** [satoshiiizuka/siggraph2016_colorization#15]
Hi,
Can't run `th colorize.lua` due to this warning. Anyone an idea how to get it working with newer libpng?

    libpng warning: Application built with libpng-1.5.18 but running with 1.6.26
    /Users/me/torch/install/bin/luajit: /Users/me/torch/install/share/lua/5.1/image/init.lua:156: [read_png] png_create_read_struct failed
    stack traceback:
        [C]: in function 'load'
        /Users/me/torch/install/share/lua/5.1/image/init.lua:156: in function 'loader'
        /Users/me/torch/install/share/lua/5.1/image/init.lua:373: in function 'load'
        colorize.lua:38: in main chunk
        [C]: in function 'dofile'
        ...me/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x0109bcad00

(OSX 10.11.6, 3.5GHz/32GB, fresh homebrew packages)

**Comment by nagadomi** [comment]
That is a problem of your torch env. You should recompile torch.
Or, reinstalling image package might fix this error.
```
luarocks install image
```

**Comment by bobbens** [comment]
As @nagadomi mentions this is an issue related to your torch install and not this repository. Please try double checking your installation and if problem persist, file a bug report at the torch repository. Closing.
