### ISSUE TITLE
Training code ?

### ISSUE THREAD

**Issue by rodrigob** [satoshiiizuka/siggraph2016_colorization#4]
Any plans to share the training code ? 
Or at least the detailed model definition ?

**Comment by bobbens** [comment]
Currently, we are not planning to release the training code.
For the model, everything is defined in the colornet.t7 file you can download with the code. You can reset it and retrain it if you want.

**Comment by smajida** [comment]
@bobbens I am going to finetune the colornet.t7 on a different dataset. Could you please kindly guide me how I can do so?
@rodrigob Hi Rodrigo, did you manage to train the model?

**Comment by tuke0919** [comment]
@smajida  Hi smajida, have you trained the network? i want to do the same thing with you

**Comment by crazyzsy** [comment]
@rodrigob Have you trained your data? How to do it?
