### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by BSVogler** [satoshiiizuka/siggraph2016_colorization#5]
Hi!
I'm new to neural networks programming but very interested in this subject.

I installed torch and luarocks.
Now
`luarocks install nn` fails with 

> nanomsg/nn.h: No such file or directory

For the other two I get 

> Error: No results matching query were found.

Do I have to install torch with Lua 5.2 and without LuaJIT?

Cheers,
Benedikt

**Comment by prov3it** [comment]
Did you compile openblas from scratch? What OS/version are you running?

**Comment by prov3it** [comment]
Did you run install-debs completely? Did you compile openblas from scratch? What OS/version are you running?

**Comment by prov3it** [comment]
Did you run install-debs completely? Did you compile openblas from scratch? What OS/version are you running?

**Comment by bobbens** [comment]
Look at http://torch.ch/docs/getting-started.html (it installs it's own copy of lua and luarocks). As this is a torch installation issue, I am closing this issue.
