### ISSUE TITLE
Ubuntu 12.04

### ISSUE THREAD

**Issue by fyngyrz** [satoshiiizuka/siggraph2016_colorization#6]
* cloned the repo, went okay
* fail: depends on lua, resolution=apt-get went okay -- (undocumented requirement)
* fail: depends on luarocks, resolution=apt-get went okay -- (undocumented requirement)
* fail: luarocks install nn fails with "lnn.c:4:23: fatal error: nanomsg/nn.h: No such file or directory" (undocumented requirement)
  * fail: nanomsg install requires npm, resolution=apt-get went okay -- (undocumented requirement)
  * fail: npm install nanomsg fails with "Error: failed to fetch from registry: nanomsg" (undocumented requirement)
    * nn depends on nanomsg -- brick wall problem

So. Any suggestions for me?

My suggestion for you is that you install this package on a fresh machine and determine what (rest of) the dependencies are, then document the full installation process.

**Comment by bobbens** [comment]
I would recommend at least Ubuntu 14.04. Please follow the instructions on http://torch.ch/docs/getting-started.html for getting torch installed (which should install all the required dependencies). I have simplified the README a bit to point to this resource.

**Comment by fyngyrz** [comment]
If you have minimum system requirements, you should state them up front. Otherwise, you may be the cause of expending people's time and effort for no worthy result.

**Comment by fyngyrz** [comment]
th colorize.lua ansel_colorado_1941.png out.png
/home/ben/torch/install/bin/luajit: /home/ben/torch/install/share/lua/5.1/torch/File.lua:370: table index is nil
stack traceback:
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:370: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/nn/Module.lua:158: in function 'read'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:353: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:353: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/nngraph/gmodule.lua:461: in function 'read'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/ben/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	colorize.lua:23: in main chunk
	[C]: in function 'dofile'
	.../ben/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x0804d540

**Comment by bobbens** [comment]
Either your colornet.t7 is corrupted or you are running out of memory. I quickly benchmarked it on one of our development systems and the peak RAM usage should be around 2 GiB for the demo in the README. Closing this now as the new error is the same as #7 , use that issue if you continue to have problems.
