### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by dbackeus** [satoshiiizuka/siggraph2016_colorization#7]
I ran the torch install on my OSX 10.11.4 (latest El Capitan), downloaded the colornet file, then tried running the example command:

```bash
th colorize.lua ansel_colorado_1941.png out.png
/Users/davidbackeus/torch/install/bin/luajit: .../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:375: unknown object
stack traceback:
	[C]: in function 'error'
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:375: in function 'readObject'
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:368: in function 'readObject'
	...s/davidbackeus/torch/install/share/lua/5.1/nn/Module.lua:158: in function 'read'
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...s/davidbackeus/torch/install/share/lua/5.1/nn/Module.lua:158: in function 'read'
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:353: in function 'readObject'
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...dbackeus/torch/install/share/lua/5.1/nngraph/gmodule.lua:461: in function 'read'
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	.../davidbackeus/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	colorize.lua:23: in main chunk
	[C]: in function 'dofile'
	...keus/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x0106fcbcf0
```

**Comment by Lauriy** [comment]
I have the same error, but before it:
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/torch/File.lua:351: $ Torch: not enough memory: you tried to allocate 0GB. Buy new RAM! at /root/torch/pkg/torch/lib/TH/THGeneral.c:222

So I'm going to try something with a bit more memory now.

**Comment by bobbens** [comment]
On my development system (arch linux x86_64 with recent install of torch + openblas) it is hitting around 2 GiB peak RAM usage for the demo image we provide. RAM does increase pretty spectacularly with image size though.

**Comment by fyngyrz** [comment]
I received this from Edgar Simo-Serra:

> Either your colornet.t7 is corrupted or you are running out of memory. I quickly benchmarked it on one of our development systems and the peak RAM usage should be around 2 GiB for the demo in the README. Closing this now as the new error is the same as #7 , use that issue if you continue to have problems.

I definitely have way more than 2 GB free. I am using the demo PNG image:

    th colorize.lua ansel_colorado_1941.png out.png

How can I tell if my colornet.t7 is corrupted? Can you provide a checksum and a means to regenerate said checksum? And the expected file size?

Perhaps a tested .gz file is called for, instead of a raw .t7 file? Or, perhaps the t7 should be part of the repo \(or... is it too big?\)

**Comment by fyngyrz** [comment]
I received this from Edgar Simo-Serra:

> Either your colornet.t7 is corrupted or you are running out of memory. I quickly benchmarked it on one of our development systems and the peak RAM usage should be around 2 GiB for the demo in the README. Closing this now as the new error is the same as #7 , use that issue if you continue to have problems.

I definitely have way more than 2 GB free. I am using the demo PNG image:

    th colorize.lua ansel_colorado_1941.png out.png

How can I tell if my colornet.t7 is corrupted? Can you provide a checksum and a means to regenerate said checksum? And the expected file size?

Perhaps a tested .gz file is called for, instead of a raw .t7 file? Or, perhaps the t7 should be part of the repo \(or... is it too big?\)

**Comment by bobbens** [comment]
Checksums are as follow:
md5sum c88fa2bb6dc9f942a492a7dc7009b966
sha1sum d397faf0b63a173680824474bfeab4725c375ca2
Expected size is 663M.

**Comment by dbackeus** [comment]
Yes, the colornet file was corrupt. After re-downloading it works!

I can actually confirm that my download was interrupted at around 10% the first time I downloaded. I then ran the script again and was surprised that it resumed form 10%. Maybe the resuming functionality is broken and it would have been better to restart the download?

**Comment by bobbens** [comment]
OK. Download script verifies integrity and memory usage is indicated in README. Going to close this issue then.

**Comment by fyngyrz** [comment]
Colornet file sha1sum and md5sum are both correct. File size is correct. Problem persists.

**Comment by franverona** [comment]
Same here

**Comment by fyngyrz** [comment]
It would appear we need to open another issue, as no response has been forthcoming.
