### ISSUE TITLE
chrominance map

### ISSUE THREAD

**Issue by lulu1315** [satoshiiizuka/siggraph2016_colorization#9]
hello and thanks for all that.
"Note that you can process a small imageto obtain the chrominance map and then rescale it and combine it with the original grayscale image for higher quality."
how would you do that ?
thanks in advance
luc

**Comment by lulu1315** [comment]
ok sorry I've get it.RGB to HSV gives me what I need.

**Comment by Ahmed-Mohamed15** [comment]
Can you explain more ? how he did that ? @lulu1315

**Comment by geppeinserra** [comment]
I have same problem. How do you obtain chrominance map of image? And how (using wich application...) can you rescale and combine it? Thanks.

**Comment by lulu1315** [comment]
I use ImageMagick ... something like this
convert imagein.png -colorspace YUV -separate image_yuv_%d.png
you will have 3 images
then resize image_yuv_%d.png and recombine
convert image_yuv_1.png image_yuv_2.png image_yuv_3.png -set colorspace YUV -combine -colorspace sRGB final.png

http://www.imagemagick.org/script/index.php

**Comment by geppeinserra** [comment]
Thank you for your precious tip. I have another question: had I to resize all the three images that I obtain with string “convert imagein.png -colorspace YUV -separate image_yuv_%d.png”? How do you make resize operation? Thank you. You are very precious for me. Geppe Inserra

**Comment by lulu1315** [comment]
imagemagick can resize : http://www.imagemagick.org/Usage/resize/

**Comment by geppeinserra** [comment]
Many thanks! Then, i have to resize with imagemagick the three images (image_yuv_0.png, image_yuv_1.png, image_yuv_2.png) that i obtain with your initial string. Is that so?

**Comment by geppeinserra** [comment]
Excuse me. I resized the three images, the i recombine… but final image loses resolution…. Sigh.

**Comment by lulu1315** [comment]
the first one (luminance) should come from your original image ... you rescale the u and v and then recombine

**Comment by geppeinserra** [comment]
Thank you very muck. Now it works!!!
